apiVersion: apps/v1
kind: Deployment
metadata:
  name: a1quest-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      name: a1quest-web
      labels:
        app: web
    spec:
      containers:
        - image: kanagatech/a1questweb:latest
          name: a1quest-web
          ports:
          - containerPort: 3000  
           
---
# Node Port Service For SpringApp
apiVersion: v1
kind: Service
metadata:
  name: a1quest-web
spec:
  type: LoadBalancer
  ports:
    - port: 80
      nodePort: 31500
      targetPort: 3000
  selector:
    app: web
